name: Build binaries and trigger deployments

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Task
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.22.5"

      - name: Install Autogit
        run: |
          curl -L $(curl -Ls -o /dev/null -w %{url_effective} https://github.com/darklab8/autogit/releases/latest | sed "s/releases\/tag/releases\/download/")/autogit-linux-amd64 -o /usr/local/bin/autogit && chmod 777 /usr/local/bin/autogit

      - name: Checkout git repo with tags and commits for autogit
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Install templ
        run: go install github.com/a-h/templ/cmd/templ@v0.2.747  
      - name: Build templ file to go
        run: templ generate
      - name: build
        run: task build:bins

      - name: Print release changelog
        id: changelog
        run: |
          echo 'artifact<<EOF' >> $GITHUB_OUTPUT
          autogit changelog >> "$GITHUB_OUTPUT"
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: upload binaries to release
        uses: softprops/action-gh-release@v2
        if: ${{startsWith(github.ref, 'refs/tags/') }}
        with:
          body: ${{ steps.changelog.outputs.artifact }}
          files: |
            dist/darkstat-linux-amd64
            dist/darkstat-linux-arm64
            dist/darkstat-macos-amd64
            dist/darkstat-macos-arm64
            dist/darkstat-windows-amd64.exe
            dist/darkstat-windows-arm64.exe
      - name: Repository Dispatch for Vanilla
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.FL_DATA_KEY }}
          repository: darklab8/fl-data-vanilla
          event-type: publish
      - name: Repository Dispatch for Discovery
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.FL_DATA_KEY }}
          repository: darklab8/fl-data-discovery
          event-type: publish
      - name: Repository Dispatch for FLSR
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.FL_DATA_KEY }}
          repository: darklab8/fl-data-flsr
          event-type: publish